onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - '@tarojs/binding'
  - '@tarojs/cli'
  - core-js
  - core-js-pure
  - esbuild

overrides:
  eslint: $eslint

patchedDependencies:
  fast-text-encoding: patches/fast-text-encoding.patch
